[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.17'
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'shibadrop/=src/',
]
#optimizer_runs = 1_000_000
optimizer_runs = 200
# via_ir = true
ignored_error_codes = []
bytecode_hash = "none"

[profile.upgradeable]
src = 'src-upgradeable/src/'

[profile.ir_inspect]
test = 'src'

[rpc_endpoints]
goerli = '${GOERLI_RPC_URL}'
mainnet = '${ETHEREUM_RPC_URL}'
puppynet = "https://puppynet.shibrpc.com/"

[etherscan]
puppynet = {key="7f80a939-7973-4249-a064-3f355244b930", chain=157, url="https://puppyscan.shib.io/"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config